### ISSUE TITLE
クラスのメソッドにおけるlogin_prohibitについて

### ISSUE THREAD

**Issue by theoremoon** [delta114514/responder-login#3]
現状の実装だと引数`self`を取るメソッドについて`login_prohibit`デコレータが正しく動作しないきがします。responderは`on_get`のようなメソッドを使うことがあるのでdjangoの`method_decorator`のようなものを用意したほうが良いのではないでしょうか（これはresponder側で導入してくれたほうが周りのライブラリ的には楽かもしれませんが）

**Comment by nagataaaas** [comment]
完全に今まで気づいてませんでした。すみません。
`responder_login.decorators`に`method_decorator`と`class_decorator`を追加しました。
